# Generated by Django 2.1.2 on 2018-11-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181101_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/wenhuang.jpg', null=True, upload_to='avatar/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
