# Generated by Django 2.1.2 on 2018-10-27 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20181025_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
