# Generated by Django 2.1.2 on 2018-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20181101_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True, verbose_name='html content'),
        ),
    ]
