# Generated by Django 2.1.2 on 2018-11-04 08:24

from django.db import migrations

def init_name(apps, schema_editor):
    # We can't import the ExampleModel model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ExampleModel = apps.get_model('learning_logs', 'ExampleModel')
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        example = ExampleModel()
        example.name = user.username
        example.save()

class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_examplemodel'),
    ]

    operations = [
        migrations.RunPython(init_name),
    ]
